"""Git wrapper for `.anvyc/` repo.

DESIGN.md §6.1 / §29.2 Phase 3. .anvyc 디렉터리를 git repo 로 관리하고
push 전 pre-commit hook 으로 secret 차단.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

GITIGNORE_CONTENT = """# auto-managed by anvyc — do not edit manually below
# 사용자 의도 외의 자동 제외 항목들
local-backups/
reports/
__pycache__/
*.pyc
.DS_Store
"""

PRECOMMIT_HOOK = """#!/usr/bin/env bash
# auto-generated by anvyc — secret scan pre-commit hook
# 환경변수 ANVYC_BIN 으로 anvyc 실행파일 override 가능 (기본: $PATH 의 anvyc).
set -euo pipefail
ANVYC_BIN="${ANVYC_BIN:-anvyc}"
if ! command -v "$ANVYC_BIN" >/dev/null 2>&1; then
    echo "anvyc pre-commit: '$ANVYC_BIN' not on PATH — hook skipped" >&2
    exit 0
fi
"$ANVYC_BIN" scan-secrets --staged --quiet --root "$(git rev-parse --show-toplevel)" || {
    echo "" >&2
    echo "anvyc pre-commit: secret scan blocked this commit." >&2
    echo "Run: $ANVYC_BIN scan-secrets --staged   to see details." >&2
    echo "Or:  git commit --no-verify   to bypass (NOT RECOMMENDED)." >&2
    exit 1
}
"""


class GitError(RuntimeError):
    pass


def _run(args: list[str], cwd: Path, *, capture: bool = False, check: bool = True) -> str:
    result = subprocess.run(
        args,
        cwd=str(cwd),
        capture_output=True,
        text=True,
    )
    if check and result.returncode != 0:
        raise GitError(
            f"{' '.join(args)} (cwd={cwd}) exit={result.returncode}\n"
            f"stderr: {result.stderr.strip()}"
        )
    return result.stdout if capture else ""


def init_repo(root: Path, *, default_branch: str = "main") -> None:
    """`.anvyc/` 를 git repo 로 초기화. .gitignore + pre-commit hook 설치."""
    root = root.resolve()
    root.mkdir(parents=True, exist_ok=True)

    if not (root / ".git").is_dir():
        _run(["git", "init", "-b", default_branch], cwd=root)

    gi = root / ".gitignore"
    if not gi.exists() or "anvyc" not in gi.read_text():
        gi.write_text(GITIGNORE_CONTENT)

    install_pre_commit_hook(root)


def install_pre_commit_hook(root: Path) -> None:
    hook_path = root / ".git" / "hooks" / "pre-commit"
    hook_path.parent.mkdir(parents=True, exist_ok=True)
    hook_path.write_text(PRECOMMIT_HOOK)
    hook_path.chmod(0o755)


def status(root: Path) -> str:
    return _run(["git", "status", "--short"], cwd=root, capture=True)


def commit(root: Path, message: str) -> str:
    _run(["git", "add", "-A"], cwd=root)
    # 변경 사항 없으면 commit 이 exit 1 — 사용자에게 "nothing to commit" 으로 친절히
    pre = _run(["git", "status", "--porcelain"], cwd=root, capture=True)
    if not pre.strip():
        return "nothing to commit"
    return _run(["git", "commit", "-m", message], cwd=root, capture=True)


def push(root: Path, remote: str = "origin", branch: str | None = None) -> str:
    args = ["git", "push", remote]
    if branch:
        args.append(branch)
    return _run(args, cwd=root, capture=True)
