#!/usr/bin/env python3
"""README '동반 도구' 표를 EXTRAS_REGISTRY SoT 에서 생성/검증.

외부 CLI 바이너리 + Python extras 의존성 메타(설치법·잠금 기능)의 단일 소스
(src/anvyc/core/extras.py)에서 README 표를 생성해 손수 유지하던 중복을 제거한다
(동반 도구 발견성 개선, step 3/3).

사용:
  python scripts/gen_extras.py            # README.md 표 in-place 갱신
  python scripts/gen_extras.py --check     # SoT 와 일치 검증 (불일치 시 exit 1)
  python scripts/gen_extras.py --print      # 생성된 표만 stdout

마커 사이 영역만 교체한다 (intro/outro prose 는 손대지 않음).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO / "src"))

from anvyc.core.extras import render_extras_markdown  # noqa: E402

BEGIN = "<!-- BEGIN companion-tools — generated by scripts/gen_extras.py (do not edit by hand) -->"
END = "<!-- END companion-tools -->"


def splice(readme_text: str, table: str) -> str:
    """README 의 BEGIN/END 마커 사이를 table 로 교체한 새 문자열 반환."""
    if BEGIN not in readme_text or END not in readme_text:
        raise SystemExit(
            f"마커를 찾지 못했습니다 — README.md 에 다음을 추가하세요:\n  {BEGIN}\n  {END}"
        )
    b = readme_text.index(BEGIN)
    e = readme_text.index(END)
    return readme_text[:b] + BEGIN + "\n" + table + "\n" + readme_text[e:]


def main() -> None:
    ap = argparse.ArgumentParser(description="README 동반 도구 표 생성/검증")
    ap.add_argument("--check", action="store_true", help="SoT 와 일치하는지만 검증 (CI/test)")
    ap.add_argument("--print", dest="print_only", action="store_true", help="표만 출력")
    args = ap.parse_args()

    table = render_extras_markdown()
    if args.print_only:
        print(table)
        return

    readme = _REPO / "README.md"
    current = readme.read_text(encoding="utf-8")
    updated = splice(current, table)

    if args.check:
        if updated != current:
            print(
                "README 동반 도구 표가 EXTRAS_REGISTRY SoT 와 불일치합니다 — "
                "`python scripts/gen_extras.py` 로 재생성하세요.",
                file=sys.stderr,
            )
            raise SystemExit(1)
        print("README 동반 도구 표: SoT 와 일치 ✓")
        return

    if updated == current:
        print("README 동반 도구 표: 이미 최신 (변경 없음)")
        return
    readme.write_text(updated, encoding="utf-8")
    print(f"updated {readme} (README 동반 도구 표)")


if __name__ == "__main__":
    main()
